### ISSUE TITLE
Override web.config

### ISSUE THREAD

**Issue by ramijarrar** [christopheranderson/azure-demeteorizer#1]
There doesn't appear to be a straightforward way to customize/override the provided web.config at the moment, this is a prohibiting factor for our deployments which rely on this file to restrict public access to staging environments.

**Comment by christopheranderson** [comment]
Great feedback. This is totally something the SDK can support. I'll add it to the backlog. 

In the meantime, you can manually replace the web.config before you run the zip command.

**Comment by christopheranderson** [comment]
This is ready in the dev branch. I'll pull to master tomorrow after I close the prereq changes.

**Comment by christopheranderson** [comment]
Added support in 0.2.0-alpha. Closing.
