### ISSUE TITLE
Version check fails with Meteor 1.3

### ISSUE THREAD

**Issue by DanielSmon** [christopheranderson/azure-demeteorizer#16]
Just tried building with Meteor 1.3, and run-precheck fails when it checks the new Meteor version:

```
sill meteor --version -> stdout: Meteor 1.3  /
ERR! main Error encountered
ERR! main meteor has an invalid version. Current version: null Valid version(s): >0.8.1 || 1.x
```

The problem appears to be that the Meteor --version output doesn't follow the semver spec correctly. I.e. it only has MAJOR.MINOR, instead of MAJOR.MINOR.PATCH.

**lib/run-precheck.js**:

```
45            var matches = result.match(/(\d+\.\d+\.\d+)/g);
```

The above resolves to null, which you can see in the ERR! output.

The simplest solution I can think of is to match MAJOR.MINOR if MAJOR.MINOR.PATCH doesn't exist. Then we can append .0 as the PATCH version if it's missing. That way, semver will continue to work, even when 1.3.1 comes along.

Thoughts?

Meanwhile, I'll fork and implement above to get me going...

**Comment by DanielSmon** [comment]
See pull request #17 for a simple solution. Happy to discuss alternatives.

**Comment by christopheranderson** [comment]
I think you made the right choice. Much of we're doing here is essentially trying to duct tape the various dependencies together, so appending 0 if it's not semver is pretty effective. Closing this thanks to your PR.
