### ISSUE TITLE
Error installing through `azure-demeteorizer install`

### ISSUE THREAD

**Issue by DanceParty** [christopheranderson/azure-demeteorizer#20]
I am getting an error with fibers when running this command. Current I have installed 

Node 0.10.40

npm 1.4.28

meteor 1.3.2.4

Visual Studio 2015

When I try that command after building successfully I am getting this error

![capture](https://cloud.githubusercontent.com/assets/10778294/15935534/6f4ab126-2e1c-11e6-8387-0ccda5aed371.PNG)

Thanks for any help!

**Comment by ramijarrar** [comment]
At the moment, the tool isn't compatible with VS2015. You should run an older version.

**Comment by DanceParty** [comment]
Is this what I should be using then? 

https://www.microsoft.com/en-us/download/details.aspx?id=23507

If so, how will I know that it works upon using Azure-demeteorizer?

Thanks a ton for the quick response btw~

**Comment by ramijarrar** [comment]
VS2010 and 2012 will definitely work.

**Comment by DanceParty** [comment]
Alright Express 2012 is downloading now... I will comment and close if I can get it to work. Thanks for the help!

**Comment by ramijarrar** [comment]
No problem. You should also be aware that there are some issues with 1.3.x apps which are currently being discussed in #9. Other than that, you should be able to build and deploy reliably (we are pushing to production with this tool).

**Comment by DanceParty** [comment]
Alright here are the steps I took and am still getting an error

Ran `azure-demeteorizer build` and it worked fine:

![build](https://cloud.githubusercontent.com/assets/10778294/15947587/2cf2bc62-2e51-11e6-8e7e-32644c857a37.PNG)

But when I run the `azure-demeteorizer install` i get this error still:

![error](https://cloud.githubusercontent.com/assets/10778294/15947601/3c94266a-2e51-11e6-8162-877b64e49566.PNG)

I went through and installed visual studio 2012 and then followed this guide (https://github.com/nodejs/node-gyp#installation) that was referenced except I installed VS2012 and ran `npm config set msvs_version 2012`. I am also running all of these commands in an administrator command prompt if that matters at all.

Thanks

**Comment by ramijarrar** [comment]
Can you paste the error from npm-debug.log?

**Comment by DanceParty** [comment]
This seems to be the only log file I can find. Hope it's the correct one.

![debug](https://cloud.githubusercontent.com/assets/10778294/15948625/aa51b032-2e56-11e6-8b88-c332e72ae90d.PNG)

**Comment by ramijarrar** [comment]
Weird that it is using Node from "Program Files" even though you have nvm installed

**Comment by ramijarrar** [comment]
Try running `npm install fibers` and paste the output.

**Comment by DanceParty** [comment]
Here is what I got. Would it possibly something with environment variables?

![fibers](https://cloud.githubusercontent.com/assets/10778294/15968280/25c2ecfc-2ee0-11e6-98ab-f666acbcc3d3.PNG)

**Comment by DanceParty** [comment]
Finally got this figured out. Not sure what would have changed it, but I added nvm/v0.10.40/ to my path, reinstalled VS 2012 Redistributable C++ update, and ran "npm install --msvs_version=2012"
