### ISSUE TITLE
Having trouble deploying to the web app

### ISSUE THREAD

**Issue by DanceParty** [christopheranderson/azure-demeteorizer#22]
I successfully build/install/zip but when I go to run 

`azure-demeteorizer deploy -s [sitename] -u [username] - p [password]`

I am running into an issue. Currently, as shown below it does not give any warnings:

![image](https://cloud.githubusercontent.com/assets/10778294/16048924/ac496580-320a-11e6-8d53-782e2b569c24.png)

However, when I navigate to my web app's url, it still displays the default "Hello world" page.

Some additional information:
Sitename: I am using the name I created for my web app (not sure if case-sensitive). I am not using a url

Username: I am using my username that was created through the deployment credentials and appending my sitename to the beginning of it `[sitename]\[username]`:

Password: I am just typing my password that I created in the deployment credentials area.

![image](https://cloud.githubusercontent.com/assets/10778294/16049024/14f85b4a-320b-11e6-8d3b-ab64f5f95fbf.png)

EDIT: I have also tried resetting the deployment credentials multiple times with no luck as well as disconnecting and reconnecting local git repository.

**Comment by ramijarrar** [comment]
You don't need to append your site name to the beginning of username. And get rid of that space in `- p`. 

Going forward, you can make sure the deploy command worked by opening your site in {sitename}.scm.azurewebsites.net and using the 'Debug console' to check the contents of wwwroot (which should contain your app). If that is okay, I would look for errors in the server logs.

**Comment by DanceParty** [comment]
Oops, must've mistyped that space in the `-p`.

Inside of my wwwroot folder is my app (within a folder called programs/server) but for some reason the web app defaults to the server.js file that came on the web app when I created it.

**Comment by ramijarrar** [comment]
Okay, you should be aware that for the time-being you need to use the `--clean` option before redeploying or manually empty out the wwwroot folder.

**Comment by DanceParty** [comment]
so that would look like `azure-demeteorizer deploy -s [sitename] -u [username] - p [password] --clean`?

**Comment by ramijarrar** [comment]
Correct, but make sure to use the dev branch:

`npm install -g christopheranderson/azure-demeteorizer#dev`

**Comment by ramijarrar** [comment]
And stop your app before deploying with that command.

**Comment by DanceParty** [comment]
Alright I will give that a shot. Thanks for the help so far!

**Comment by DanceParty** [comment]
Alright this is what I am getting with the `azure-demeteorizer deploy -s [sitename] -u [username] - p [password] --clean` command

![image](https://cloud.githubusercontent.com/assets/10778294/16059350/7cfe1fb4-3237-11e6-84cf-d6b2d6e7d8e6.png)

**Comment by DanceParty** [comment]
I am running --loglevel silly now

**Comment by DanceParty** [comment]
so when I ran that, I am getting a long error that essentially saying file name must be less than 260 characters and that the path is too long

**Comment by ramijarrar** [comment]
You are on 1.3.x right?

**Comment by ramijarrar** [comment]
It's a known issue for 1.3.x apps, you'll need to either downgrade to 1.2.x or wait for Git-based deployments in #9 which should be implemented soon.

**Comment by DanceParty** [comment]
Alright I will try downgrading until that comes out then. Thanks for the help!

Just to clarify. You can downgrade by running `meteor create myapp --release 1.2.1`?

**Comment by DanceParty** [comment]
So i created a new app through Meteor 1.2.1 and it ran fine out of the box on the Azure WebApp Services. Then I re-downloaded all of the packages that I was using in my previous application and then transferred all of the code over and am now getting an error during deployment that says 

`An error has occurred. Exception Message: The process cannot access the file \\wwwroot\\programs\\server\\node_modules\\fibers\\bin\\...\\fibers.node because it is being used by another process`

Any suggestions?

**Comment by DanceParty** [comment]
Update: I thought I had already stopped my WebApp but I was checking the wrong one. Stopping it solved the problem. Thanks!
