### ISSUE TITLE
Check for prereqs before running install

### ISSUE THREAD

**Issue by christopheranderson** [christopheranderson/azure-demeteorizer#3]
As pointed out in #2, there are several dependencies that are required to do native module compilation appropriately for deployment. 

In order to install all the appropriate dependencies, we need to check for the existence of required software being installed.

Example:
- Node 0.10.40 32
- Python 2.7
- VS C++ Redistributable
- (Other dependencies for Native Module compilation)
- (currently) Windows OS

We should allow a `--force` option on install to continue even if prechecks fail.

Might be useful to have a `--test` feature which will only run prechecks.

**Comment by ramijarrar** [comment]
In the meantime. can we list these in readme?

**Comment by christopheranderson** [comment]
I'm going to try and get these out tonight. If I'm delayed, I'll make a spot update to the readme. :)

**Comment by ramijarrar** [comment]
:+1:

**Comment by christopheranderson** [comment]
Added support in 0.2.0-alpha. Closing.
