### ISSUE TITLE
Azure Node version instructions

### ISSUE THREAD

**Issue by ramijarrar** [christopheranderson/azure-demeteorizer#6]
The DEFAULT_NODE_VERSION setting specified in the readme isn't mentioned on the [Azure docs](https://azure.microsoft.com/en-gb/documentation/articles/nodejs-specify-node-version-azure-apps/#versioning-websites-with-app-settings) and doesn't seem to actually do anything when we use it. Is this a typo (WEBSITE_NODE_DEFAULT_VERSION is the setting added to node applications by default), or are we doing something incorrectly here?

**Comment by christopheranderson** [comment]
This is a typo. I'll update it. Nice catch.

**Comment by christopheranderson** [comment]
Fixed in 22c3875
